### ISSUE TITLE
question: pcb masks images DPI

### ISSUE THREAD

**Issue by tablatronix** [cnlohr/esp8266_link_test#1]
Thanks for posting those
I am assuming

https://raw.githubusercontent.com/cnlohr/esp8266_link_test/master/hardware/esp12e-generics-F_Cu.png

is 600 dpi 

and

https://github.com/cnlohr/esp8266_link_test/blob/master/hardware/esp_micro85-only-F_Cu.png

is 1200 dpi ?

is this correct ?

**Comment by cnlohr** [comment]
Yes.  That is correct.  I probably should just do everything at 1200 dpi. Additionally, the metadata in the .png stores this information.  It makes it possible to drag-and-drop the png on things like OpenOffice Writer, and it will automatically scale to precisely the correct size.

**Comment by cnlohr** [comment]
Just added a readme!  First time I've used the web gui to commit stuff!

**Comment by tablatronix** [comment]
My ancient version of fireworks was not resampling properly. Thanks.
